### ISSUE TITLE
No APK Signing Block before ZIP Central Directory

### ISSUE THREAD

**Issue by Juziwsw** [Jay-Goo/ProtectedApkResignerForWalle#30]
请问下,这是什么原因

**Comment by Juziwsw** [comment]
![1568207903(1)](https://user-images.githubusercontent.com/21341172/64700599-c33c2000-d4d9-11e9-9429-a9775d66e901.jpg)

**Comment by Juziwsw** [comment]
com.meituan.android.walle.SignatureNotFoundException: No APK Signing Block before ZIP Central Directory
        at com.meituan.android.walle.ApkUtil.findApkSigningBlock(ApkUtil.java:165)
        at com.meituan.android.walle.PayloadWriter.handleApkSigningBlock(PayloadWriter.java:164)
        at com.meituan.android.walle.PayloadWriter.putAll(PayloadWriter.java:98)
        at com.meituan.android.walle.PayloadWriter.put(PayloadWriter.java:75)
        at com.meituan.android.walle.PayloadWriter.put(PayloadWriter.java:48)
        at com.meituan.android.walle.ChannelWriter.putRaw(ChannelWriter.java:101)
        at com.meituan.android.walle.ChannelWriter.put(ChannelWriter.java:76)
        at com.meituan.android.walle.ChannelWriter.put(ChannelWriter.java:49)
        at com.meituan.android.walle.commands.BatchCommand.generateChannelApk(BatchCommand.java:81)
        at com.meituan.android.walle.commands.BatchCommand.parse(BatchCommand.java:65)
        at com.meituan.android.walle.Main.main(Main.java:51)

**Comment by xuexiangjys** [comment]
我也出现了同样的问题

**Comment by smileklvens** [comment]
要使用未签名的包
