### ISSUE TITLE
app_aligned_signed.apk无法找到

### ISSUE THREAD

**Issue by xinghun2019** [Jay-Goo/ProtectedApkResignerForWalle#37]
{"ret":-1,"msg":"get signature failed, File:D:\ProtectedApkResignerForWalle\app_aligned_signed.apk Not Found"}
java.io.FileNotFoundException: Source 'D:\ProtectedApkResignerForWalle\app_aligned_signed.apk' does not exist
        at org.apache.commons.io.FileUtils.checkFileRequirements(FileUtils.java:1405)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1072)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1040)
        at com.meituan.android.walle.commands.BatchCommand.generateChannelApk(BatchCommand.java:80)
        at com.meituan.android.walle.commands.BatchCommand.parse(BatchCommand.java:65)
        at com.meituan.android.walle.Main.main(Main.java:51)
app_aligned.apk生成成功了，但是后面又提示app_aligned_signed无法找到

**Comment by panguojian** [comment]
我也遇到了这个问题，请问解决了吗

**Comment by ailibin** [comment]
我也是这个问题，不知道是什么问题，博主可以回答一下么
