### ISSUE TITLE
渠道包打不出来，config配置过了，app-release_aligned.apk已生成但app-release_aligned_signed.apk未生成

### ISSUE THREAD

**Issue by wangyangke** [Jay-Goo/ProtectedApkResignerForWalle#6]
{"ret":-1,"msg":"get signature failed, File:C:\Users\wangyangke\Desktop\python_apk\app-release_aligned_signed.apk Not Found"}
java.io.FileNotFoundException: Source 'C:\Users\wangyangke\Desktop\python_apk\app-release_aligned_signed.apk' does not exist
        at org.apache.commons.io.FileUtils.checkFileRequirements(FileUtils.java:1405)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1072)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1040)
        at com.meituan.android.walle.commands.BatchCommand.generateChannelApk(BatchCommand.java:80)
        at com.meituan.android.walle.commands.BatchCommand.parse(BatchCommand.java:65)
        at com.meituan.android.walle.Main.main(Main.java:51)
java.io.FileNotFoundException: Source 'C:\Users\wangyangke\Desktop\python_apk\app-release_aligned_signed.apk' does not exist
        at org.apache.commons.io.FileUtils.checkFileRequirements(FileUtils.java:1405)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1072)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1040)
        at com.meituan.android.walle.commands.BatchCommand.generateChannelApk(BatchCommand.java:80)
        at com.meituan.android.walle.commands.BatchCommand.parse(BatchCommand.java:65)
        at com.meituan.android.walle.Main.main(Main.java:51)

**Comment by wangyangke** [comment]
app-release_aligned.apk生成了，但是app-release_aligned_signed.apk没有看到

**Comment by JinJieGu** [comment]
看log是重签名时失败了，检查下签名信息对吗。如果还不行，把你的config.py贴给我

**Comment by wangyangke** [comment]
#!/usr/bin/python  
#-*-coding:utf-8-*-

#keystore信息
#Windows 下路径分割线请注意使用\\转义
keystorePath = "D:/xxd_git/android_xxd_2017/app/xinxindai.keystore"
keyAlias = "新新贷"
keystorePassword = "yongxin"
keyPassword = "yongxin"

#加固后的源文件名（未重签名）
protectedSourceApkName = "app-release.encrypted.apk"

#Android SDK buidtools path , please use above 26.0+
sdkBuildToolPath = "D:/android/sdk/build-tools/26.0.2"

**Comment by wangyangke** [comment]
签名信息没错

**Comment by wangyangke** [comment]
#!/usr/bin/python  
#-*-coding:utf-8-*-

#keystore信息
#Windows 下路径分割线请注意使用\\转义
keystorePath = "D://xxd_git/xinxindai.keystore"
keyAlias = "xxx"
keystorePassword = "xxx"
keyPassword = "xxx"

#加固后的源文件名（未重签名）
protectedSourceApkName = "app-release.encrypted.apk"

#Android SDK buidtools path , please use above 26.0+
sdkBuildToolPath = "D://android/sdk/build-tools/26.0.2"

**Comment by wangyangke** [comment]
#!/usr/bin/python
#--coding:utf-8--

#keystore信息
#Windows 下路径分割线请注意使用\转义
keystorePath = "D:\\xxd_git\\xinxindai.keystore"
keyAlias = "xxx"
keystorePassword = "xxx"
keyPassword = "xxx"

#加固后的源文件名（未重签名）
protectedSourceApkName = "app-release.encrypted.apk"

#Android SDK buidtools path , please use above 26.0+
sdkBuildToolPath = "D:\\android\\sdk\\build-tools\\26.0.2"

**Comment by wangyangke** [comment]
我config中需不需要将/改成\，我是windows电脑，同事mac可以成功生成，那是我这不行，不知道是不是这个原因

**Comment by wangyangke** [comment]
上面是有两个斜杠，发出来只有一个了

**Comment by JinJieGu** [comment]
看起来并没有什么问题，你把验证签名和写渠道的shell代码注释掉，看看签名shell提示什么错误，有没有正常生成签名包

**Comment by wangyangke** [comment]
就是没有生成签名包报错，验证签名和写渠道的shell代码注释掉之后没什么错误信息输出，我加你QQ了，方便QQ交流下吗

**Comment by sh1tge** [comment]
我这里也出现了同样的错误信息
但是测试demo apk 又没问题 好奇怪

**Comment by SunnyLy** [comment]
360加固成功后，再拿加固包打渠道包，渠道写入成功，但是用【360显危镜】检测加固信息时，显示未加固，这是什么原因呀，在线等 。

**Comment by JinJieGu** [comment]
@SunnyLy 360显危镜加固显示未加固，但是360加固平台显示“应用已经被加密保护，无法重复进行加固”
，所以应该是成功加固了，可能他们检测的机制不同吧

**Comment by wang642357** [comment]
你好，我也遇到了这个问题，请问是怎么解决的

**Comment by muzilikunpeng** [comment]
您好，这个问题最后是怎么解决的

**Comment by muzilikunpeng** [comment]
@JinJieGu @wangyangke 请问这个问题是怎么解决的，在线等

**Comment by skylarklxlong** [comment]
您好！我也遇到了同样的问题，报错日志都是一样的，请问这个问题目前解决了吗？

**Comment by ansuote** [comment]
我也出现这个问题，并且解决了。我的原因是密码中字符没有转义，比如 & 要改成  \& 。大家看下这个日志上面，还有其他错误信息，可以帮助定位。

**Comment by wishkity** [comment]
我今天也出现了这个问题，最终发现是360加固后的apk有问题，90多M的apk加固出来只有10多M，应该是公司网络的问题。重新下载，然后再执行写入渠道就没问题了。

**Comment by zhangtuodd** [comment]
mac环境也报错：同样是password转义的问题。我是这样解决的：#注：& $ （）#  都需要在前面加上\来转义

**Comment by yangdong125845** [comment]
我也遇到了这个问题 config配置过了，生成了一个中间包，但是渠道包没有生成，打包过程到Verification succesful就结束了。

**Comment by fxdong** [comment]
我也遇到了同样的问题，最后发现是自己config.py的sdkBuildToolPath路径配置错了

**Comment by hanaandalice** [comment]
我遇到Not Found没找到apk看ApkResigner.py代码，是因为名字做了_aligned拼接
#加固后的源文件名（未重签名）
protectedSourceApkName = "app.apk"
实际我的源文件名叫：app_aligned.apk
还有个是我路径反斜杠开始写的不对的问题，以上成功打包

**Comment by chengqiuxia** [comment]
我遇到的Not Found 没签名成功，是因为，SDK的apksigner做了加密无法访问。也就是本身sdk中的签名命令不可用。解密后正常使用，打包。
