### ISSUE TITLE
window10测试，报错

### ISSUE THREAD

**Issue by KobeBryant824** [Jay-Goo/ProtectedApkResignerForWalle#9]
//用腾讯乐固加固，加固前已经签名，keystore已经放在桌面了
Verification succesful
Failed to load signer "signer #1"
java.io.FileNotFoundException: ?C:\Users\a-Hai\Desktop\release.keystore (文件名、目录名或卷标语法不正确。)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at com.android.apksigner.ApkSignerTool$SignerParams.loadKeyStoreFromFile(ApkSignerTool.java:733)
        at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCertsFromKeyStore(ApkSignerTool.java:636)
        at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCerts(ApkSignerTool.java:580)
        at com.android.apksigner.ApkSignerTool$SignerParams.access$200(ApkSignerTool.java:534)
        at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:229)
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:87)
{"ret":-1,"msg":"get signature failed, File:E:\Android\app\ProtectedApkResignerForWalle\app-release_legu_aligned_signed.apk Not Found"}
java.io.FileNotFoundException: Source 'E:\Android\app\ProtectedApkResignerForWalle\app-release_legu_aligned_signed.apk' does not exist
        at org.apache.commons.io.FileUtils.checkFileRequirements(FileUtils.java:1405)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1072)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1040)
        at com.meituan.android.walle.commands.BatchCommand.generateChannelApk(BatchCommand.java:80)
        at com.meituan.android.walle.commands.BatchCommand.parse(BatchCommand.java:65)
        at com.meituan.android.walle.Main.main(Main.java:51)

**Comment by KobeBryant824** [comment]
#!/usr/bin/python  
#-*-coding:utf-8-*-

#keystore信息
#Windows 下路径分割线请注意使用\\转义
keystorePath = "‪C:\\Users\\a-Hai\\Desktop\\release.keystore"
keyAlias = "testres"
keystorePassword = "testres"
keyPassword = "testres"

#加固后的源文件名（未重签名）
protectedSourceApkName = "app-release_legu.apk"

#Android SDK buidtools path , please use above 25.0+
sdkBuildToolPath = "E:\\Android\\Sdk\\build-tools\\25.0.3"

**Comment by KobeBryant824** [comment]
#!/usr/bin/python  
#-*-coding:utf-8-*-
#已经添加了转义字符了，github自动转换了

#keystore信息
#Windows 下路径分割线请注意使用\\转义
keystorePath = "‪C:\\Users\\a-Hai\\Desktop\\release.keystore"
keyAlias = "testres"
keystorePassword = "testres"
keyPassword = "testres"

#加固后的源文件名（未重签名）
protectedSourceApkName = "app-release_legu.apk"

#Android SDK buidtools path , please use above 25.0+
sdkBuildToolPath = "E:\\Android\\Sdk\\build-tools\\25.0.3"

**Comment by JinJieGu** [comment]
亲测没问题，看log是你的签名文件路径的问题，请确认你的路径无误，保证你粘贴路径不带任何格式

**Comment by KobeBryant824** [comment]
路径前多了个？号，是编码格式问题，现在可以拿到聚道了

**Comment by marren06** [comment]
@KobeBryant824  怎么拿到的？ 我的一直报错  获取签名失败  
![image](https://user-images.githubusercontent.com/17778482/82298050-20cc2900-99e6-11ea-97dd-46875754a449.png)

签名文件路径各种方法都试了 还是不行
